package com.movietime.domain.model

data class TvShowDetail(
    val adult: Boolean,
    val backdropUrl: String,
    val createdBy: List<ShowCreator>,
    val episodeRunTime: List<Int>,
    val firstAirDate: String,
    val genres: List<Genre>,
    val homepage: String,
    val id: Int,
    val inProduction: Boolean,
    val languages: List<String>,
    val lastAirDate: String,
    val lastEpisodeToAir: Episode,
    val name: String,
    val nextEpisodeToAir: Episode?,
    val networks: List<Network>,
    val numberOfEpisodes: Int,
    val numberOfSeasons: Int,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalName: String,
    val overview: String,
    val popularity: Double,
    val posterUrl: String,
    val productionCompanies: List<Company>,
    val productionCountries: List<Country>,
    val seasons: List<Season>,
    val spokenLanguages: List<Language>,
    val status: String,
    val tagline: String,
    val type: String,
    val voteAverage: Double,
    val voteCount: Int
)